// Each value must be byte-exact with a key written into history.changes by the
// server's recordHistory() calls — the activity-log search matches with
// LIKE %"value"% against the JSON column.
export const ACTIVITY_FIELDS = [
  { value: 'status', label: 'Status' },
  { value: 'qualityLevel', label: 'Quality Level' },
  { value: 'qaLevelId', label: 'QA Level ID' },
  { value: 'priority', label: 'Priority' },
  { value: 'dueDate', label: 'Due Date' },
  { value: 'description', label: 'Description' },
  { value: 'poNumber', label: 'PO Number' },
  { value: 'quoteReference', label: 'Quote Reference' },
  { value: 'isRepeatJob', label: 'Repeat Job' },
  { value: 'repeatJobReference', label: 'Repeat Job Reference' },
  { value: 'contactId', label: 'Contact (ID)' },
  { value: 'contactName', label: 'Contact Name' },
  { value: 'companyName', label: 'Company Name' },
  { value: 'contactPhone', label: 'Contact Phone' },
  { value: 'contactEmail', label: 'Contact Email' },
  { value: 'jobNumber', label: 'Job Number' },
  { value: 'archived', label: 'Archived' },
  { value: 'invoicedDate', label: 'Invoiced Date' },
  { value: 'assignees', label: 'Assignees' },
  { value: 'labourRate', label: 'Labour Rate' },
  { value: 'labourOt1Override', label: 'Overtime 1 Hours (override)' },
  { value: 'labourOt1Total', label: 'Overtime 1 Total' },
  { value: 'labourOt2Override', label: 'Overtime 2 Hours (override)' },
  { value: 'labourOt2Total', label: 'Overtime 2 Total' },
  { value: 'labourHolidayOverride', label: 'Public Holiday Hours (override)' },
  { value: 'labourHolidayTotal', label: 'Public Holiday Total' },
  { value: 'labourSpecialHours', label: 'Special Labour Hours' },
  { value: 'labourSpecialRate', label: 'Special Labour Rate' },
  { value: 'materialsCost', label: 'Materials Cost' },
  { value: 'materialsProfitPercent', label: 'Materials Profit %' },
  { value: 'subcontractorCost', label: 'Subcontractor Cost' },
  { value: 'subcontractorProfitPercent', label: 'Subcontractor Profit %' },
  { value: 'grandTotal', label: 'Grand Total' },
  { value: 'timer', label: 'Timer' },
  { value: 'timeEntryId', label: 'Time Entry ID' },
  { value: 'itemNumber', label: 'Item Number' },
  { value: 'machineNumber', label: 'Machine Number' },
  { value: 'qty', label: 'Quantity' },
  { value: 'startTime', label: 'Start Time' },
  { value: 'endTime', label: 'End Time' },
  { value: 'note', label: 'Note' },
];
