// Each value must be byte-exact with a key written into history.changes by the
// server's recordHistory() calls — the activity search matches it against the names
// of the recorded changes (routes/search.js). A value ending in '*' matches every
// recorded name starting with the rest: a part's edits are recorded under per-part
// names ("part … added", "part …"), so they are found through "part *".
// This list is a hand-kept copy of what the server records: a new key recorded by a
// recordHistory() call must be added here, and a key no call writes any more removed,
// or the picker offers names that never match (as itemNumber/companyId once did).
export const ACTIVITY_FIELDS = [
  { value: 'status', label: 'Status' },
  { value: 'qualityLevel', label: 'Quality Level' },
  { value: 'priority', label: 'Priority' },
  { value: 'dueDate', label: 'Due Date' },
  { value: 'description', label: 'Description' },
  { value: 'poNumber', label: 'PO Number' },
  { value: 'quoteReference', label: 'Quote Reference' },
  { value: 'isRepeatJob', label: 'Repeat Job' },
  { value: 'repeatJobReference', label: 'Repeat Job Reference' },
  { value: 'contactName', label: 'Contact Name' },
  { value: 'companyName', label: 'Company Name' },
  { value: 'jobNumber', label: 'Job Number' },
  { value: 'archived', label: 'Archived' },
  { value: 'invoicedDate', label: 'Invoiced Date' },
  { value: 'inspectionSignOff', label: 'Inspection Sign-off Skipped' },
  { value: 'assignees', label: 'Assignees' },
  { value: 'labourHoursOverride', label: 'Normal Hours (override)' },
  { value: 'labourRate', label: 'Labour Rate' },
  { value: 'labourTotal', label: 'Normal Labour Total' },
  { value: 'labourOt1Override', label: 'Overtime 1 Hours (override)' },
  { value: 'labourOt1MultiplierOverride', label: 'Overtime 1 Multiplier (override)' },
  { value: 'labourOt1Total', label: 'Overtime 1 Total' },
  { value: 'labourOt2Override', label: 'Overtime 2 Hours (override)' },
  { value: 'labourOt2MultiplierOverride', label: 'Overtime 2 Multiplier (override)' },
  { value: 'labourOt2Total', label: 'Overtime 2 Total' },
  { value: 'labourHolidayOverride', label: 'Public Holiday Hours (override)' },
  { value: 'labourHolidayTotal', label: 'Public Holiday Total' },
  { value: 'labourSpecialHours', label: 'Special Labour Hours' },
  { value: 'labourSpecialRate', label: 'Special Labour Rate' },
  { value: 'labourSpecialDescription', label: 'Special Labour Note' },
  { value: 'materialsCost', label: 'Materials Cost' },
  { value: 'materialsProfitPercent', label: 'Materials Profit %' },
  { value: 'materialsDescription', label: 'Materials Note' },
  { value: 'subcontractorCost', label: 'Subcontractor Cost' },
  { value: 'subcontractorProfitPercent', label: 'Subcontractor Profit %' },
  { value: 'subcontractorDescription', label: 'Subcontractor Note' },
  { value: 'grandTotal', label: 'Grand Total' },
  { value: 'timer', label: 'Timer' },
  { value: 'timeEntryId', label: 'Time Entry ID' },
  { value: 'part *', label: 'Parts (added, changed, removed)' },
  { value: 'item', label: 'Part Worked On' },
  { value: 'worker', label: 'Worker' },
  { value: 'file', label: 'File' },
  { value: 'machineNumber', label: 'Machine Number' },
  { value: 'qty', label: 'Quantity' },
  { value: 'startTime', label: 'Start Time' },
  { value: 'endTime', label: 'End Time' },
  { value: 'note', label: 'Note' },
  { value: 'jobCardPreviewed', label: 'Job Card Previewed' },
  { value: 'jobCardPrinted', label: 'Job Card Printed' },
  { value: 'attachmentsPrinted', label: 'Attachments Printed' },
  { value: 'packetSaved', label: 'Print Packet Saved' },
  // Only ever written by the startup conversion (old entries), never by live code.
  { value: 'packetBuilt', label: 'Print Packet Built' },
];
